/**
 * The console's look, as one style table — the pattern the other OpenSA apps use (`viewer-styles.ts`,
 * `debug-styles.ts`). Dark, flat and dense on purpose: an operations surface is read at a glance for eight
 * hours, so contrast goes to the data and nothing else competes with the map.
 */
import type { CSSProperties } from 'react';

export const COLORS = {
  accent: '#38bdf8',
  border: '#1c2735',
  danger: '#f43f5e',
  muted: '#7b8a9c',
  panel: '#0b1017',
  panelRaised: '#111926',
  text: '#e8eef6',
} as const;

const MONO = 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace';

export const styles = {
  app: {
    background: '#05070a',
    color: COLORS.text,
    display: 'grid',
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
    fontSize: 12,
    gridTemplateColumns: '300px 1fr 264px',
    gridTemplateRows: '44px 1fr 26px',
    height: '100%',
    width: '100%',
  },
  badge: {
    borderRadius: 3,
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: 0.4,
    padding: '2px 6px',
  },
  button: {
    background: COLORS.panelRaised,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 4,
    color: COLORS.text,
    cursor: 'pointer',
    fontSize: 11,
    padding: '4px 9px',
  },
  buttonPrimary: {
    background: '#0e3a52',
    border: `1px solid ${COLORS.accent}`,
    borderRadius: 4,
    color: COLORS.accent,
    cursor: 'pointer',
    fontSize: 11,
    padding: '4px 9px',
  },
  canvas: { display: 'block', height: '100%', width: '100%' },
  canvasWrap: { minHeight: 0, overflow: 'hidden', position: 'relative' },
  detail: {
    background: 'rgba(11, 16, 23, 0.94)',
    border: `1px solid ${COLORS.border}`,
    borderRadius: 6,
    bottom: 14,
    left: 14,
    maxWidth: 380,
    padding: '10px 12px',
    position: 'absolute',
    zIndex: 3,
  },
  empty: { color: COLORS.muted, fontStyle: 'italic', padding: '10px 12px' },
  fill: { height: '100%', left: 0, position: 'absolute', top: 0, width: '100%' },
  logLine: {
    borderBottom: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    fontFamily: MONO,
    fontSize: 10,
    padding: '3px 12px',
  },
  mono: { fontFamily: MONO },
  panel: {
    background: COLORS.panel,
    borderRight: `1px solid ${COLORS.border}`,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    overflow: 'hidden',
  },
  panelRight: {
    background: COLORS.panel,
    borderLeft: `1px solid ${COLORS.border}`,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    overflow: 'hidden',
  },
  panelTitle: {
    borderBottom: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1.2,
    padding: '8px 12px',
    textTransform: 'uppercase',
  },
  row: {
    borderBottom: `1px solid ${COLORS.border}`,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    padding: '7px 12px',
  },
  rowSelected: {
    background: '#0d1d2b',
    borderLeft: `2px solid ${COLORS.accent}`,
    paddingLeft: 10,
  },
  scroll: { flex: 1, minHeight: 0, overflowY: 'auto' },
  statusBar: {
    alignItems: 'center',
    background: COLORS.panel,
    borderTop: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    display: 'flex',
    fontFamily: MONO,
    fontSize: 10,
    gap: 16,
    gridColumn: '1 / -1',
    padding: '0 12px',
  },
  topBar: {
    alignItems: 'center',
    background: COLORS.panel,
    borderBottom: `1px solid ${COLORS.border}`,
    display: 'flex',
    gap: 14,
    gridColumn: '1 / -1',
    padding: '0 14px',
  },
} satisfies Record<string, CSSProperties>;
