/**
 * The console's look, as one style table — the pattern the other OpenSA apps use (`viewer-styles.ts`,
 * `debug-styles.ts`). Dark, flat and dense on purpose: an operations surface is read at a glance for eight
 * hours, so contrast goes to the data and nothing else competes with the map.
 */
import type { CSSProperties } from 'react';

export const COLORS = {
  accent: '#38bdf8',
  border: '#1c2735',
  danger: '#f43f5e',
  muted: '#7b8a9c',
  panel: '#0b1017',
  panelRaised: '#111926',
  text: '#e8eef6',
} as const;

const MONO = 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace';

export const styles = {
  app: {
    background: '#05070a',
    color: COLORS.text,
    display: 'grid',
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
    fontSize: 12,
    gridTemplateColumns: '300px 1fr 264px',
    gridTemplateRows: '44px 1fr 30px 26px',
    height: '100%',
    width: '100%',
  },
  /** Phone: one column — map fills the screen, the lists live in a sheet under it. */
  appCompact: {
    background: '#05070a',
    color: COLORS.text,
    display: 'grid',
    fontFamily: 'ui-sans-serif, system-ui, sans-serif',
    fontSize: 12,
    gridTemplateColumns: '1fr',
    gridTemplateRows: '40px 1fr 44% 30px 20px',
    height: '100%',
    width: '100%',
  },
  badge: {
    borderRadius: 3,
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: 0.4,
    padding: '2px 6px',
  },
  button: {
    background: COLORS.panelRaised,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 4,
    color: COLORS.text,
    cursor: 'pointer',
    fontSize: 11,
    padding: '4px 9px',
  },
  buttonPrimary: {
    background: '#0e3a52',
    border: `1px solid ${COLORS.accent}`,
    borderRadius: 4,
    color: COLORS.accent,
    cursor: 'pointer',
    fontSize: 11,
    padding: '4px 9px',
  },
  // `touchAction: none` is load-bearing on a phone: without it the browser claims the drag for scrolling
  // and page-zoom before a single `pointermove` reaches the gesture layer.
  canvas: { display: 'block', height: '100%', touchAction: 'none', width: '100%' },
  canvasWrap: { minHeight: 0, overflow: 'hidden', position: 'relative' },
  degradedBanner: {
    background: 'rgba(120, 72, 8, 0.92)',
    border: '1px solid #d08b2c',
    borderRadius: 5,
    color: '#ffe8c4',
    fontSize: 11,
    left: 10,
    padding: '5px 10px',
    position: 'absolute',
    right: 10,
    top: 10,
    zIndex: 4,
  },
  detail: {
    background: 'rgba(11, 16, 23, 0.94)',
    border: `1px solid ${COLORS.border}`,
    borderRadius: 6,
    bottom: 14,
    left: 14,
    maxWidth: 380,
    padding: '10px 12px',
    position: 'absolute',
    zIndex: 3,
  },
  detailCompact: {
    background: 'rgba(11, 16, 23, 0.96)',
    border: `1px solid ${COLORS.border}`,
    borderRadius: 6,
    bottom: 8,
    left: 8,
    padding: '9px 11px',
    position: 'absolute',
    right: 8,
    zIndex: 3,
  },
  empty: { color: COLORS.muted, fontStyle: 'italic', padding: '10px 12px' },
  fill: { height: '100%', left: 0, position: 'absolute', top: 0, width: '100%' },
  inventoryButton: {
    background: COLORS.accent,
    border: 'none',
    borderRadius: 4,
    color: '#05070a',
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    marginTop: 2,
    padding: '5px 8px',
  },
  /** Shown only when the clipboard is unavailable — a LAN dev server is not a secure context. */
  inventoryFallback: {
    background: '#05070a',
    border: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    fontFamily: MONO,
    fontSize: 9,
    height: 90,
    marginTop: 4,
    width: '100%',
  },
  /** 201/1-01. Bottom-left so it never sits under the selection panel, and narrow enough for 360 CSS px. */
  inventoryPanel: {
    background: 'rgba(11, 16, 23, 0.94)',
    border: `1px solid ${COLORS.accent}`,
    borderRadius: 6,
    bottom: 10,
    color: COLORS.text,
    display: 'grid',
    fontFamily: MONO,
    fontSize: 10,
    gap: 3,
    left: 10,
    maxWidth: 240,
    padding: '6px 8px',
    position: 'absolute',
    zIndex: 5,
  },
  inventoryWarn: {
    color: '#ffb454',
  },
  logLine: {
    borderBottom: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    fontFamily: MONO,
    fontSize: 10,
    padding: '3px 12px',
  },
  mono: { fontFamily: MONO },
  panel: {
    background: COLORS.panel,
    borderRight: `1px solid ${COLORS.border}`,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    overflow: 'hidden',
  },
  panelRight: {
    background: COLORS.panel,
    borderLeft: `1px solid ${COLORS.border}`,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    overflow: 'hidden',
  },
  panelTitle: {
    borderBottom: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1.2,
    padding: '8px 12px',
    textTransform: 'uppercase',
  },
  row: {
    borderBottom: `1px solid ${COLORS.border}`,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    padding: '7px 12px',
  },
  rowSelected: {
    background: '#0d1d2b',
    borderLeft: `2px solid ${COLORS.accent}`,
    paddingLeft: 10,
  },
  scroll: { flex: 1, minHeight: 0, overflowY: 'auto' },
  /** The phone sheet's tab strip. */
  sheetTab: {
    background: 'transparent',
    border: 'none',
    borderBottom: `2px solid transparent`,
    color: COLORS.muted,
    cursor: 'pointer',
    flex: 1,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1,
    padding: '9px 0',
  },
  sheetTabActive: {
    borderBottom: `2px solid ${COLORS.accent}`,
    color: COLORS.text,
  },
  sheetTabs: {
    background: COLORS.panel,
    borderTop: `1px solid ${COLORS.border}`,
    display: 'flex',
  },
  statusBar: {
    alignItems: 'center',
    background: COLORS.panel,
    borderTop: `1px solid ${COLORS.border}`,
    color: COLORS.muted,
    display: 'flex',
    fontFamily: MONO,
    fontSize: 10,
    gap: 16,
    gridColumn: '1 / -1',
    padding: '0 12px',
  },
  /** The shift timeline strip (201/8-03). Sits above the status bar, full width. */
  timeline: {
    alignItems: 'center',
    background: COLORS.panel,
    borderTop: `1px solid ${COLORS.border}`,
    display: 'flex',
    gap: 10,
    gridColumn: '1 / -1',
    padding: '0 12px',
  },
  /** The scrub track itself — it takes what the row has left. */
  timelineRange: {
    flex: 1,
    minWidth: 60,
  },
  /** REPLAY, shown while the console is NOT live. Deliberately loud: the whole screen is showing the past,
   *  and an operator who misses that is reading an old picture as the current one. */
  timelineReplay: {
    background: '#4a1220',
    borderRadius: 3,
    color: '#ffb3c0',
    fontFamily: MONO,
    fontSize: 10,
    letterSpacing: 0.6,
    padding: '2px 6px',
  },
  topBar: {
    alignItems: 'center',
    background: COLORS.panel,
    borderBottom: `1px solid ${COLORS.border}`,
    display: 'flex',
    gap: 14,
    gridColumn: '1 / -1',
    padding: '0 14px',
  },
} satisfies Record<string, CSSProperties>;
