import { defineConfig, devices } from '@playwright/test';

/**
 * E2E + visual-regression lane (plan 046, Iteration 8). Separate from `npm test` (Vitest, headless
 * node units) — it boots the real Vite app + the static asset server and drives a browser. Targets
 * the self-contained object-viewer, whose fixtures live in the gitignored `tests/viewer/` (generated by
 * `npm run test:fixtures`, served at `/viewer`; no 700 MB WIMG archive needed) and are loaded only in
 * `--mode e2e`.
 *
 * RENDERER (changed by plan 074/13 phase 4): the viewers run on our own WebGPU engine, so headless
 * Chromium needs WebGPU explicitly enabled — the same flags the bench harness uses
 * (`tools-debug/bench-harness/drive.js`). SwiftShader has no WebGPU, so the old "software renderer =
 * deterministic screenshots" premise is gone: canvas baselines are now produced by the real GPU and are
 * MACHINE-SPECIFIC. This lane does not run in CI (fixtures need a local GTA copy), which is what makes
 * that acceptable; regenerate with `npm run e2e:update` after any renderer change.
 */
// Dedicated e2e port (not the usual 5173 dev port) so the lane never reuses a hand-started dev server that
// might be in another mode (e.g. the `local` bring-your-own-files loader). The e2e server always boots with
// `--mode e2e`, loading the committed `.env.e2e` (which forces the deterministic fetch loader).
const APP_PORT = 5174;
const STATIC_PORT = 3001;

export default defineConfig({
  expect: { toHaveScreenshot: { maxDiffPixelRatio: 0.02 } },
  forbidOnly: !!process.env.CI,
  fullyParallel: true,
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: { args: ['--enable-unsafe-webgpu', '--enable-features=WebGPU', '--use-angle=metal'] },
      },
    },
  ],
  reporter: 'list',
  retries: process.env.CI ? 2 : 0,
  testDir: './e2e',
  use: {
    baseURL: `http://localhost:${APP_PORT}`,
    trace: 'on-first-retry',
  },
  webServer: [
    {
      command: 'npm run serve:static',
      reuseExistingServer: !process.env.CI,
      timeout: 60_000,
      url: `http://localhost:${STATIC_PORT}/viewer/objects/manifest.json`,
    },
    {
      command: `npm run dev -- --mode e2e --port ${APP_PORT} --strictPort`,
      reuseExistingServer: !process.env.CI,
      timeout: 120_000,
      url: `http://localhost:${APP_PORT}`,
    },
  ],
  workers: process.env.CI ? 1 : undefined,
});
