import { parseDff } from '@opensa/renderware/parsers/binary/dff';
import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { capNightSet } from '../../plugins/conform-night';
import { fingerprintClump } from './prelit-context';

/**
 * Real-asset prelight fingerprint (plan 019) over the SF Chinatown victorian that motivated only-mode's
 * `nightMax`: its night set is DARK at the median while the window glow lives in the p95 tail — the class the
 * statistical repair cannot reach (the median test doesn't see it, the tail guard protects it), so the manual
 * cap exists. The DFF comes from stock gta3.img (regenerated by `npm run test:fixtures` into the gitignored
 * `fixtures/original/`).
 */
const FIXTURE = 'fixtures/original/world/newvic1_sfw.dff';
const haveFixture = existsSync(FIXTURE);

function loadClump(): ReturnType<typeof parseDff> {
  const bytes = readFileSync(FIXTURE);

  return parseDff(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));
}

describe.skipIf(!haveFixture)('prelit fingerprint + night cap on newvic1_sfw (real asset)', () => {
  describe('negative cases', () => {
    it('the statistical profile hides the glow: night median is dark, the glow is only a tail', () => {
      const fingerprint = fingerprintClump(loadClump())!;

      expect(fingerprint.hasNight).toBe(true);
      expect(fingerprint.nightP50).toBeLessThan(32); // "dark at night" by the median — auto repair skips it
      expect(fingerprint.nightP95).toBeGreaterThan(100); // …while the windows glow in the tail
    });
  });

  describe('positive cases', () => {
    it('capNightSet flattens the glow tail and leaves the dark body untouched', () => {
      const clump = loadClump();
      const before = fingerprintClump(clump)!;
      for (const geometry of clump.geometries) {
        if (geometry.nightColors) {
          capNightSet(geometry.nightColors, 40);
        }
      }
      const after = fingerprintClump(clump)!;

      expect(after.nightP95).toBeLessThanOrEqual(41); // glow capped (±1 rounding)
      expect(after.nightP50).toBeCloseTo(before.nightP50, 0); // dark walls untouched
      expect(after.dayP50).toBe(before.dayP50); // day set never touched
    });
  });
});
