import { parseDff } from '@opensa/renderware/parsers/binary/dff';
import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import type { Placement, SeamModel } from './seam-weld';

import { computeSeamOverrides } from './seam-weld';

/**
 * Real-asset seam weld (plan 016) over two **co-located San Fierro crack-factory shells** that share boundary
 * geometry — a genuine cross-model prelit seam with differing prelit. The DFFs come from stock gta3.img
 * (regenerated by `npm run test:fixtures` into the gitignored `fixtures/original/`); the placements are their
 * stock IPL instances (US 1.0).
 */
const A = {
  name: 'cf_ext_dem_sfs',
  path: 'fixtures/original/world/cf_ext_dem_sfs.dff',
  placement: { position: [-2166.875, -236.515625, 40.859375], rotation: [0, 0, 0, 1] } as Placement,
};
const B = {
  name: 'crackfact_sfs',
  path: 'fixtures/original/world/crackfact_sfs.dff',
  placement: { position: [-2166.867188, -236.5078125, 40.8671875], rotation: [0, 0, 0, 1] } as Placement,
};
const haveFixtures = existsSync(A.path) && existsSync(B.path);

/** How many of a model's overrides actually change its prelit (RGB differs from the source at that position). */
function reconciledCount(
  model: SeamModel,
  overrides: readonly { pos: readonly number[]; rgb: readonly number[] }[],
): number {
  const original = new Map<string, [number, number, number]>();
  for (const geometry of model.geometries) {
    for (let v = 0; v < geometry.positions.length / 3; v += 1) {
      const key = `${geometry.positions[v * 3]}|${geometry.positions[v * 3 + 1]}|${geometry.positions[v * 3 + 2]}`;
      original.set(key, [geometry.prelit[v * 4], geometry.prelit[v * 4 + 1], geometry.prelit[v * 4 + 2]]);
    }
  }

  return overrides.filter((override) => {
    const source = original.get(`${override.pos[0]}|${override.pos[1]}|${override.pos[2]}`);

    return source ? source.some((channel, i) => channel !== override.rgb[i]) : false;
  }).length;
}

/** Read a fixture DFF into a SeamModel (its prelit geometries + a given placement). */
function seamModel(fixture: typeof A, placement: Placement): SeamModel {
  const clump = parseDff(new Uint8Array(readFileSync(fixture.path)).buffer);
  const geometries = clump.geometries
    .filter((geometry) => geometry.prelitColors)
    .map((geometry) => ({
      positions: geometry.positions,
      prelit: geometry.prelitColors!,
      triangles: geometry.triangles.map((triangle) => ({ a: triangle.a, b: triangle.b, c: triangle.c })),
    }));

  return { geometries, name: fixture.name, placement };
}

describe.skipIf(!haveFixtures)('computeSeamOverrides (real San Fierro crack-factory pair)', () => {
  describe('negative cases', () => {
    it('welds nothing when the two models are placed 100 units apart', () => {
      const far: Placement = {
        position: [B.placement.position[0] + 100, B.placement.position[1], B.placement.position[2]],
        rotation: B.placement.rotation,
      };
      const { stats } = computeSeamOverrides([seamModel(A, A.placement), seamModel(B, far)]);
      expect(stats.welded).toBe(0);
    });
  });

  describe('positive cases', () => {
    it('welds the shared boundary at the stock placements — both models get reconciling overrides', () => {
      const modelA = seamModel(A, A.placement);
      const modelB = seamModel(B, B.placement);
      const { overrides, stats } = computeSeamOverrides([modelA, modelB]);

      expect(stats.welded).toBeGreaterThan(0);
      expect(stats.modelsTouched).toBe(2);
      const overridesA = overrides.get(A.name) ?? [];
      const overridesB = overrides.get(B.name) ?? [];
      expect(overridesA.length).toBeGreaterThan(0);
      expect(overridesB.length).toBeGreaterThan(0);
      // The two shells carry different prelit at the seam, so the mean must actually change at least one side.
      expect(reconciledCount(modelA, overridesA) + reconciledCount(modelB, overridesB)).toBeGreaterThan(0);
    });
  });
});
