/**
 * Regenerate `src/core/opcodes.generated.ts` from the vendored Sanny Builder library
 * (`vendor/sa.json`, pin recorded in `vendor/README.md`). Run via `npm run cleo:opcodes`.
 *
 * One row per opcode id: `[id, name, numParams, flags, extensionIndex]`. When the same id appears in
 * several extensions (41 ids do), the FIRST extension in {@link EXTENSION_PRIORITY} wins — SAMPFUNCS
 * sits last because its SA-MP reassignments conflict with the CLEO+ meanings (`0B21` is the one real
 * arity conflict in the 1.62 library), and SA-MP is out of scope for the runtime anyway.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface Library {
  readonly extensions: readonly { readonly commands: readonly LibraryCommand[]; readonly name: string }[];
  readonly meta: { readonly version: string };
}

interface LibraryCommand {
  readonly attrs?: Readonly<Record<string, boolean>>;
  readonly id: string;
  readonly input?: readonly { readonly type: string }[];
  readonly name: string;
  readonly num_params: number;
  readonly output?: readonly { readonly type: string }[];
}

/** First hit wins; extensions not listed here go after the listed ones, in file order. */
const EXTENSION_PRIORITY = ['default', 'CLEO', 'CLEO+', 'NewOpcodes'];
const LAST = ['SAMPFUNCS'];

const FLAG_VARIADIC = 1;
const FLAG_CONDITION = 2;
const FLAG_BRANCH = 4;

const root = dirname(fileURLToPath(import.meta.url));
const library = JSON.parse(readFileSync(join(root, '../vendor/sa.json'), 'utf8')) as Library;

const ordered = [...library.extensions].sort((a, b) => rank(a.name) - rank(b.name));
const rows = new Map<number, string>();
const extensions: string[] = [];
let dropped = 0;

for (const extension of ordered) {
  const extIndex = extensions.push(extension.name) - 1;
  for (const command of extension.commands) {
    const id = Number.parseInt(command.id, 16);
    if (rows.has(id)) {
      dropped += 1;
      continue;
    }
    // Byte order in the stream is inputs then outputs; a variadic tail ('arguments') is read until the
    // 0x00 terminator, so the emitted arity is the number of DECLARED operand reads before that tail.
    const params = [...(command.input ?? []), ...(command.output ?? [])];
    const variadicAt = params.findIndex((p) => p.type === 'arguments');
    const declared = variadicAt >= 0 ? variadicAt : command.num_params;
    const flags =
      (variadicAt >= 0 ? FLAG_VARIADIC : 0) |
      (command.attrs?.is_condition ? FLAG_CONDITION : 0) |
      (command.attrs?.is_branch ? FLAG_BRANCH : 0);
    rows.set(
      id,
      `[0x${command.id.toUpperCase()}, ${JSON.stringify(command.name)}, ${declared}, ${flags}, ${extIndex}]`,
    );
  }
}

function rank(name: string): number {
  const first = EXTENSION_PRIORITY.indexOf(name);
  if (first >= 0) {
    return first;
  }

  return LAST.includes(name) ? 1_000_000 : 1_000;
}

const sorted = [...rows.entries()].sort(([a], [b]) => a - b).map(([, row]) => row);
const out = `/* eslint-disable */
// prettier-ignore-start
// GENERATED by scripts/generate-opcodes.ts from vendor/sa.json (Sanny Builder library ${library.meta.version},
// pin in vendor/README.md) — ${sorted.length} opcodes, ${dropped} duplicate ids dropped by extension priority.
// Do not edit; run \`npm run cleo:opcodes\`.

/** \`[id, name, numParams, flags, extensionIndex]\` — see \`opcode-table.ts\` for the decoded shape. */
export type OpcodeRow = readonly [number, string, number, number, number];

export const OPCODE_EXTENSIONS: readonly string[] = ${JSON.stringify(extensions)};

// prettier-ignore
export const OPCODE_ROWS: readonly OpcodeRow[] = [
${sorted.map((row) => `  ${row},`).join('\n')}
];
// prettier-ignore-end
`;

writeFileSync(join(root, '../src/core/opcodes.generated.ts'), out);
// eslint-disable-next-line no-console -- a generator's summary line is its whole UI
console.log(
  `generated ${sorted.length} opcode rows (${dropped} duplicates dropped) across ${extensions.length} extensions`,
);
