import type { RWClump, RWGeometry } from '@opensa/renderware/parsers/binary/types';

import { parseDff } from '@opensa/renderware/parsers/binary/dff';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { buildModelMesh, meshBounds } from './mesh-builder';

const IDENTITY = [1, 0, 0, 0, 1, 0, 0, 0, 1];

/** A clump of one atomic → one geometry, placed by a single frame (rotation 3×3 flatten + position). */
function clump(geo: RWGeometry, rotation = IDENTITY, position: [number, number, number] = [0, 0, 0]): RWClump {
  return {
    atomics: [{ frameIndex: 0, geometryIndex: 0 }],
    frames: [{ name: '', parentIndex: -1, position, rotation }],
    geometries: [geo],
  };
}

/** A one-triangle geometry textured `texture`, with the given vertex positions. */
function geometry(positions: number[], texture: string): RWGeometry {
  return {
    materials: [{ texture: { name: texture } }],
    normals: null,
    positions: new Float32Array(positions),
    prelitColors: null,
    triangles: [{ a: 0, b: 1, c: 2, materialIndex: 0 }],
    uvLayers: [],
  } as unknown as RWGeometry;
}

const TRI = [0, 0, 0, 2, 0, 0, 0, 2, 0]; // a flat triangle in the XY plane

/** A one-triangle geometry with explicit prelit (day) + optional night vertex colours. */
function coloured(prelit: null | number[], night: null | number[]): RWGeometry {
  return {
    materials: [{ texture: { name: 'bark' } }],
    nightColors: night ? new Uint8Array(night) : null,
    normals: null,
    positions: new Float32Array(TRI),
    prelitColors: prelit ? new Uint8Array(prelit) : null,
    triangles: [{ a: 0, b: 1, c: 2, materialIndex: 0 }],
    uvLayers: [],
  } as unknown as RWGeometry;
}

const DAY = [40, 40, 40, 255, 40, 40, 40, 255, 40, 40, 40, 255];
const NIGHT = [8, 9, 10, 255, 8, 9, 10, 255, 8, 9, 10, 255];

describe('buildModelMesh', () => {
  describe('negative cases', () => {
    it('omits nightColors when no source geometry has a night set', () => {
      expect(buildModelMesh(clump(coloured(DAY, null))).nightColors).toBeUndefined();
    });
  });

  describe('positive cases', () => {
    it('carries the source night colours through to the merged mesh', () => {
      expect([...buildModelMesh(clump(coloured(DAY, NIGHT))).nightColors!]).toEqual(NIGHT);
    });

    it('buckets triangles by texture and keeps model-local positions under the identity frame', () => {
      const mesh = buildModelMesh(clump(geometry(TRI, 'bark')));

      expect(mesh.groups).toHaveLength(1);
      expect(mesh.groups[0].texture).toBe('bark');
      expect([...mesh.groups[0].indices]).toEqual([0, 1, 2]);
      expect([...mesh.positions]).toEqual(TRI);
      expect([...mesh.colors]).toEqual(new Array(12).fill(255)); // opaque white where source had no prelit
    });

    it('applies the frame translation to every vertex', () => {
      const mesh = buildModelMesh(clump(geometry(TRI, 'bark'), IDENTITY, [10, 20, 30]));

      expect([...mesh.positions]).toEqual([10, 20, 30, 12, 20, 30, 10, 22, 30]);
    });
  });
});

// A real model carrying day + night vertex colours (regenerated by `npm run test:fixtures`, gitignored).
const NIGHT_FIXTURE = 'tests/original/dff/night-colours/cedar1_hi.dff';
const ab = (u: Uint8Array): ArrayBuffer => u.buffer.slice(u.byteOffset, u.byteOffset + u.byteLength) as ArrayBuffer;

describe('buildModelMesh night colours (real fixture)', () => {
  describe('positive cases', () => {
    it('carries the source per-vertex night set into the merged mesh', () => {
      const clump = parseDff(ab(new Uint8Array(readFileSync(NIGHT_FIXTURE))));
      const mesh = buildModelMesh(clump);

      expect(mesh.nightColors).toBeDefined();
      expect(mesh.nightColors!.length).toBe((mesh.positions.length / 3) * 4);
      expect([...mesh.nightColors!.slice(0, 4)]).toEqual([...clump.geometries[0].nightColors!.slice(0, 4)]);
    });
  });
});

describe('meshBounds', () => {
  describe('positive cases', () => {
    it('returns the axis-aligned min/max of the vertices', () => {
      const bounds = meshBounds(buildModelMesh(clump(geometry([0, 0, 0, 2, 0, 5, -1, 2, 0], 'bark'))));

      expect(bounds.min).toEqual([-1, 0, 0]);
      expect(bounds.max).toEqual([2, 2, 5]);
    });
  });
});
