/**
 * Asset registration for generated LOD models: allocate a free object id per model, emit an IDE `objs` section,
 * and splice an `IDE` line into `gta.dat` (IDEs load before IPLs). Shared by the LOD tools.
 */

/** Search window for free object ids: above the low special-model ranges, below the model ceiling.
 *
 *  **19000, raised from the stock 18630 (the user's call, 2026-08-10).** 18630 is a fact about a plain 1.0 —
 *  ids above it silently fail to load there, which is the "HD swapped, no LOD" symptom. The target always
 *  carries FLA, whose DFF range is `0 - 19999` (its own log prints it), so budgeting to the stock number was
 *  designing down to a ceiling the target does not have — silent by construction, per
 *  `docs/restrictions/sa-target.md`. 19000 keeps ~1000 ids of FLA headroom rather than spending the range. */
const ID_MIN = 4000;
const ID_MAX = 19000;
/** Default object flags for LOD billboards — the value the Proper-Fixes LOD-vegetation mod uses for tree LODs.
 *  (0x200084: alpha + draw-last + LOD-friendly.) */
const DEFAULT_FLAGS = 2097284;

/** IMG entry names are ≤ 23 bytes incl `.dff`; the model name is the entry base, so it must be ≤ 19 chars. */
const MAX_MODEL = 19;

/**
 * Assign each model a free object id — the lowest unused ids in the stock space (**not** necessarily contiguous;
 * ids needn't be consecutive, and a heavily-modded game rarely has a wide contiguous gap left below the
 * ceiling). Deterministic (models sorted, ids ascending). See {@link ID_MAX} for what the ceiling is a fact about.
 */
export function allocateLodIds(models: readonly string[], used: ReadonlySet<number>): Map<string, number> {
  const sorted = [...new Set(models.map((m) => m.toLowerCase()))].sort();
  const free = freeIds(used, sorted.length);
  const ids = new Map<string, number>();
  sorted.forEach((model, i) => ids.set(model, free[i]));

  return ids;
}

/** An IDE `objs` section text — one row per model `id, model, txd, drawDistance, flags`, ordered by id. */
export function buildLodIde(
  ids: ReadonlyMap<string, number>,
  txd: string,
  drawDistance: number,
  flags: number = DEFAULT_FLAGS,
): string {
  const rows = [...ids]
    .sort((a, b) => a[1] - b[1])
    .map(([model, id]) => `${id}, ${model}, ${txd}, ${drawDistance}, ${flags}`);

  return [`# Generated by @opensa/map-placement — LOD models (${txd})`, 'objs', ...rows, 'end', ''].join('\r\n');
}

/**
 * The model name SA registers for a generated LOD (IDE `objs` + the `<model>.dff` IMG entry). Usually the LOD's
 * own name; when that would overflow the IMG entry limit, a short synthetic `<prefix><index>` alias (the DFF still
 * references its real texture inside the shared TXD, so visuals are unaffected).
 */
export function lodAlias(name: string, index: number, prefix = 'lodt'): string {
  const lower = name.toLowerCase();

  return lower.length <= MAX_MODEL ? lower : `${prefix}${index}`;
}

/** Splice `IDE <path>` into gta.dat right after the last IDE line (so it loads before the IPLs). */
export function patchGtaDat(dat: string, idePath: string): string {
  const eol = dat.includes('\r\n') ? '\r\n' : '\n';
  const lines = dat.split(/\r?\n/);
  const insert = `IDE ${idePath}`;
  // Insert **before the first IPL/ZON placement** — the game loads gta.dat top-down, so a model referenced by an
  // (even stock) IPL must be defined by an IDE that appears earlier. Appending after the *last* IDE was wrong when
  // a mod had already appended its own `IDE` lines past the IPL section (the new IDE then loaded too late → the
  // placements that reference its ids hit `undefined ID` and crash).
  const firstIpl = lines.findIndex((line) => /^\s*IPL\b/i.test(line));
  if (firstIpl >= 0) {
    lines.splice(firstIpl, 0, insert);

    return lines.join(eol);
  }
  // No IPL section — keep the IDEs grouped (after the last one), else prepend.
  let lastIde = -1;
  lines.forEach((line, i) => {
    if (/^\s*IDE\b/i.test(line)) {
      lastIde = i;
    }
  });
  if (lastIde < 0) {
    lines.unshift(insert);
  } else {
    lines.splice(lastIde + 1, 0, insert);
  }

  return lines.join(eol);
}

/**
 * Rewrite the DRAW DISTANCE of the named `objs` models in an IDE text, leaving every other row, comment and
 * line ending untouched. Returns the new text and which models were changed.
 *
 * This is how a baked clutter layer gets its range (plan 014). Stock `data/maps/generic/procobj.ide` declares
 * all 107 procobj models at **59**, which is why SA's runtime scatter pops in so close; ProperFixes ships the
 * same file at **299** — one metre under the 300 threshold that puts an object on SA's big-building path — and
 * that is the whole mechanism behind their layer's range. No new ids: the stock row IS the declaration.
 *
 * **Only the 5-cell `id, model, txd, drawDist, flags` form is edited.** SA also has a variant carrying a mesh
 * count and several draw distances; a requested model in any other shape is returned in `skipped` rather than
 * guessed at, because a silently unchanged draw distance is invisible until someone measures the range.
 */
export function setIdeDrawDistance(
  text: string,
  models: ReadonlySet<string>,
  distance: number,
): { changed: string[]; skipped: string[]; text: string } {
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const changed: string[] = [];
  const skipped: string[] = [];
  let section = '';
  const lines = text.split(/\r?\n/).map((line) => {
    const bare = line.split('#')[0].trim();
    if (bare === '') {
      return line;
    }
    if (!bare.includes(',')) {
      section = bare.toLowerCase() === 'end' ? '' : bare.toLowerCase();

      return line;
    }
    if (section !== 'objs') {
      return line;
    }
    const cells = bare.split(',').map((cell) => cell.trim());
    const model = (cells[1] ?? '').toLowerCase();
    if (!models.has(model)) {
      return line;
    }
    if (cells.length !== 5) {
      skipped.push(model);

      return line;
    }
    changed.push(model);

    return `${cells[0]}, ${cells[1]}, ${cells[2]}, ${distance}, ${cells[4]}`;
  });

  return { changed, skipped, text: lines.join(eol) };
}

/** The lowest `count` unused ids within `[ID_MIN, ID_MAX]` (ascending; gaps allowed). */
function freeIds(used: ReadonlySet<number>, count: number): number[] {
  const ids: number[] = [];
  for (let id = ID_MIN; id <= ID_MAX && ids.length < count; id += 1) {
    if (!used.has(id)) {
      ids.push(id);
    }
  }
  if (ids.length < count) {
    throw new Error(`only ${ids.length} free object ids in [${ID_MIN}, ${ID_MAX}], need ${count}`);
  }

  return ids;
}
