import { splitByMedian } from './streamed-areas';

/** One object to bake as a permanent text-IPL row — no LOD partner, no stream record. */
export interface PermanentPlacement {
  readonly id: number;
  readonly interior: number;
  readonly model: string;
  readonly position: readonly [number, number, number];
  readonly rotation: readonly [number, number, number, number];
}

/**
 * Rows per area text IPL.
 *
 * An area's rows pass through SA's `gpLoadedBuildings` boot buffer, which stock sizes at 4 096 and OLA's
 * `EntitiesPerIpl = unlimited` lifts. **The largest anyone has been measured RUNNING on the target is 9 627** —
 * ProperFixes' vegetation layer, 6 files of ~9 600 permanent rows and no streams
 * (`docs/gta-sa-original/reference-install-config.md`).
 *
 * Sized just under it deliberately, and the reasoning is the lesson of `map-placement/002`: **prefer margin
 * where there is no lift over margin where there is a demonstrated one.** The 40-slot `IplEntityIndexArrays`
 * has no lift at all (`EntityIpl = unlimited` is set and does not work — measured twice), so slots are the
 * scarce resource and rows are not. A smaller cap here buys buffer margin nobody needs and spends slots that
 * cannot be bought back.
 *
 * What 002 got wrong, so it is not repeated: PF's 9 627 is rows in a text IPL with **zero** streams. Using it
 * as a budget for text rows + their stream records together overflowed the buffer at 8 520 and crashed on the
 * first area. This path emits text rows ONLY, which is why the same number applies here.
 */
export const AREA_MAX_ROWS = 9600;

/**
 * Emit placements as **permanent text IPLs**, ProperFixes' shape: per spatial area one `<areaBase><i>.ipl`
 * registered in `gta.dat`, every row `lod = -1`, and no binary streams at all.
 *
 * Why this rather than the HD+LOD streamed pairs of {@link buildLinkedAreas} (plan 014): `CIplStore` only loads
 * a stream's IPL slot while the player is inside its bounding box grown by 190 units, so a streamed row cannot
 * draw at any distance its tile is not resident for — our 512-instance tiles gate the layer at ~190 m whatever
 * the IDE says. A permanent row has no such gate, so range comes from the IDE (299, one metre under SA's
 * 300 big-building threshold) and the LOD twin that used to buy the range is not needed: it recovered ~0.2 % of
 * a hand-modelled bush's geometry for the price of a whole entity.
 *
 * `instBearingFiles` is every emitted file, since each carries rows — returned so the slot budget is READ off
 * the emitter rather than re-derived, which is how plan 007's written-down budget went stale in silence.
 */
export function buildPermanentAreas(
  placements: readonly PermanentPlacement[],
  areaBase: string,
  maxRows = AREA_MAX_ROWS,
): { datLines: string[]; files: [string, string][]; instBearingFiles: number } {
  if (placements.length === 0) {
    return { datLines: [], files: [], instBearingFiles: 0 };
  }
  const datLines: string[] = [];
  const files: [string, string][] = [];

  splitByMedian(placements, maxRows, (placement) => placement.position).forEach((area, index) => {
    const areaName = `${areaBase}${index}`;
    const rows = area.map(
      ({ id, interior, model, position, rotation }) =>
        `${id}, ${model}, ${interior}, ${[...position, ...rotation].join(', ')}, -1`,
    );
    datLines.push(`IPL DATA\\MAPS\\${areaName}.IPL`);
    files.push([
      `${areaName}.ipl`,
      ['# Generated by @opensa/map-placement — permanent area (plan 103)', 'inst', ...rows, 'end', ''].join('\r\n'),
    ]);
  });

  return { datLines, files, instBearingFiles: files.length };
}
