/**
 * Regenerate `src/whitelist/whitelist.generated.ts` from the two live sources (the VM handler
 * registry and the vendored opcode DB via `deriveWhitelist`). Run via `npm run cleo:whitelist`.
 * A CI drift test fails when this file no longer matches what regeneration would produce.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { deriveWhitelist } from '../src/whitelist/derive';

const { dual, vmServed } = deriveWhitelist();

const hex = (id: number): string => `0x${id.toString(16).padStart(4, '0')}`;
const rows = (ids: readonly number[]): string => ids.map(hex).join(', ');

const out = `// GENERATED by cleo/sdk/scripts/generate-whitelist.ts (\`npm run cleo:whitelist\`) from the VM
// handler registry and the vendored Sanny DB — ${dual.length} dual-target of ${vmServed.length} VM-served opcodes.
// Do not edit; the drift test in whitelist.test.ts fails when this file is stale.

/** Served by our VM AND runnable under plain real CLEO 4 on SA 1.0 US. */
export const DUAL_TARGET_OPCODES: ReadonlySet<number> = new Set([
  ${rows(dual)},
]);

/** Every opcode the VM's handler registry serves — the hard ceiling for any target. */
export const VM_SERVED_OPCODES: ReadonlySet<number> = new Set([
  ${rows(vmServed)},
]);
`;

const root = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(root, '../src/whitelist/whitelist.generated.ts'), out);
console.log(`[cleo-sdk] whitelist regenerated: ${dual.length} dual-target / ${vmServed.length} VM-served`);
