import { parseVehicleAudioSettings } from '@opensa/renderware/parsers/text/vehicle-audio.parser';
/**
 * Guards on the BAKED stock table (204, 2026-09-11).
 *
 * The file is 212 rows of recovered data with no code in it, which is exactly the kind of thing that rots
 * unwatched: it is regenerated by `scripts/debug/bake-vehicle-audio.ts` from a checkout of the reversed game
 * that this repository does not vendor, so nothing else would notice a re-bake that lost rows, mangled a
 * column, or quietly wrote a tree's name into the fleet.
 *
 * These assert VALUES, not shapes. A row whose numbers are all readable but wrong is the failure worth
 * catching, and the three spot-checked here are cross-checkable by hand against
 * [what the columns mean](../../../docs/gta-sa-original/vehicle-audio-settings.md).
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const BAKED = join(dirname(fileURLToPath(import.meta.url)), '..', 'data', 'vehicle-audio-settings.cfg');

const parsed = parseVehicleAudioSettings(readFileSync(BAKED, 'latin1'));
const byModel = new Map(parsed.rows.map((row) => [row.model, row]));

describe('the baked stock vehicle audio table', () => {
  describe('negative cases', () => {
    it('parses with NO problems — a legend line that reads as a broken row is a defect in the bake', () => {
      // The first bake wrote its header with `#`, which is `audio-events.dat`'s marker and not this
      // format's. Eleven comment lines came back as broken rows. The marker here is `;`.
      expect(parsed.problems).toEqual([]);
    });

    it('carries no row past the fleet', () => {
      // The array is 232 entries because that is the slot count the game reserves; ids 612-614 name nothing
      // and 615 onward are VEGETATION. A bake that emitted all 232 would put tree names in the table.
      expect(byModel.has('veg_tree3')).toBe(false);
      expect(byModel.has('veg_palm04')).toBe(false);
    });

    it('names no model twice', () => {
      expect(byModel.size).toBe(parsed.rows.length);
    });
  });

  describe('positive cases', () => {
    it('carries every one of San Andreas 212 vehicles', () => {
      // 400..611 with no gaps — the whole stock fleet, which is what makes this a replacement for the
      // adjuster's file rather than a partial one.
      expect(parsed.rows).toHaveLength(212);
      expect(parsed.rows[0]?.model).toBe('landstal');
    });

    it('gives a police car an emergency radio that is SWITCHED OFF rather than absent', () => {
      // The trap this table is written down for: a radio switched off is the id 13, while -1 would be
      // `RADIO_INVALID`. A bake that confused the two would silently change what the car does.
      const copcarla = byModel.get('copcarla');

      expect(copcarla?.radioStation).toBe(13);
      expect(copcarla?.radioType).toBe('emergency');
      expect(copcarla?.soundType).toBe('car');
    });

    it('gives each car the two engine banks the dummy loops come out of', () => {
      // The player bank and the dummy bank are consecutive and DIFFERENT; a bake that read one column twice
      // would leave every car voiced by the wrong pair and nothing would look wrong.
      const landstal = byModel.get('landstal');

      expect(landstal?.playerBank).toBe(99);
      expect(landstal?.dummyBank).toBe(98);
    });

    it('keeps the authored floats rather than rounding them', () => {
      // `0.69999999` is what the executable holds. Rounding it to 0.7 would be this repository editing the
      // original's data, which is the one thing the goals forbid.
      expect(byModel.get('infernus')?.bassFactor).toBeCloseTo(0.89999998, 8);
      expect(byModel.get('infernus')?.bassSetting).toBe('boost');
    });

    it('marks an ambulance a van-doored emergency vehicle', () => {
      const ambulan = byModel.get('ambulan');

      expect(ambulan?.doorType).toBe('van');
      expect(ambulan?.radioType).toBe('emergency');
    });
  });
});
