/**
 * What a built HTML entry actually SHIPS: every chunk it reaches by static import, raw and gzipped, and
 * every source module inside those chunks with the generated bytes attributed to it.
 *
 * Why it exists. 201/1-01's bundle column was measured by hand on 2026-08-09 and left no instrument behind,
 * so the "after" half of [1/06](../../docs/plans/201-dispatch-console/1-the-map-profile/readme.md) had no
 * way to be the same measurement as the "before". A before/after where the two sides were produced by
 * different one-off scripts is not an A/B (`CLAUDE.md`).
 *
 * What it measures, precisely:
 *
 * - **the static import graph only.** A chunk reached by `import()` is DOWNLOADED LATER, not shipped with
 *   the page, and counting it hides the number the entry is judged on. The pak worker is the case that
 *   matters here — it is a separate chunk by design (2/02), and it must not land in this total.
 * - **gzip, not brotli.** It is the floor every server gives us, so it is the honest wire number.
 * - **source attribution by sourcemap walk**: the generated bytes between consecutive mapping segments,
 *   which is what source-map-explorer does. Bytes with no mapping are reported as `(unmapped)` rather than
 *   spread over the neighbours — a runtime helper the bundler injected is not a source file's cost.
 *
 * Run (the build must carry sourcemaps, or attribution is skipped and says so):
 *
 * ```sh
 * npm run build -- --base=./ --sourcemap
 * npx tsx scripts/debug/bundle-inventory.ts --entry dispatch.html [--dist dist] [--top 25] [--json out.json]
 * ```
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { gzipSync } from 'node:zlib';

interface ChunkReading {
  bytesGzip: number;
  bytesRaw: number;
  name: string;
}

interface SourceReading {
  bytes: number;
  chunk: string;
  source: string;
}

/** `import"./x.js"` / `from"./x.js"` — the static edges. `import(` is deliberately NOT matched. */
const STATIC_IMPORT = /(?:^|[\s;}])(?:import|export)[^"'()]*["']([^"']+\.js)["']/g;

function argValue(name: string, fallback: string): string {
  const at = process.argv.indexOf(name);

  return at >= 0 && process.argv[at + 1] ? process.argv[at + 1] : fallback;
}

/**
 * Generated bytes per source, from a chunk's sourcemap. The VLQ decode is deliberately minimal: only the
 * generated column and the source index are needed, and pulling a library in for that would put a
 * dependency in a debug script.
 */
function attribute(dist: string, chunk: string): SourceReading[] {
  const mapPath = join(dist, 'assets', `${chunk}.map`);
  if (!existsSync(mapPath)) {
    return [];
  }
  const map = JSON.parse(readFileSync(mapPath, 'utf8')) as { mappings: string; sources: string[] };
  const code = readFileSync(join(dist, 'assets', chunk), 'utf8');
  const lineLengths = code.split('\n').map((l) => l.length + 1);
  const bytes = new Map<string, number>();
  let sourceIndex = 0;
  let previous: null | { column: number; line: number; source: number } = null;
  const flushTo = (line: number, column: number): void => {
    if (previous === null) {
      return;
    }
    let span = 0;
    if (line === previous.line) {
      span = column - previous.column;
    } else {
      span = lineLengths[previous.line] - previous.column;
      for (let l = previous.line + 1; l < line; l += 1) {
        span += lineLengths[l] ?? 0;
      }
      span += column;
    }
    const name = map.sources[previous.source] ?? '(unknown)';
    bytes.set(name, (bytes.get(name) ?? 0) + Math.max(0, span));
  };

  map.mappings.split(';').forEach((lineSegments, line) => {
    let column = 0;
    for (const segment of lineSegments.split(',')) {
      if (segment === '') {
        continue;
      }
      const fields = decodeVlq(segment);
      column += fields[0];
      if (fields.length >= 4) {
        sourceIndex += fields[1];
        flushTo(line, column);
        previous = { column, line, source: sourceIndex };
      }
    }
  });
  // The tail after the last mapping belongs to whatever the last segment named.
  flushTo(lineLengths.length - 1, 0);

  const mapped = [...bytes.values()].reduce((sum, n) => sum + n, 0);
  const unmapped = Buffer.byteLength(code) - mapped;
  const rows = [...bytes.entries()].map(([source, size]) => ({ bytes: size, chunk, source }));
  if (unmapped > 0) {
    rows.push({ bytes: unmapped, chunk, source: '(unmapped — bundler runtime, banners, glue)' });
  }

  return rows;
}

/** Every chunk the entry HTML names, plus everything those chunks statically import, transitively. */
function reachableChunks(dist: string, entryHtml: string): string[] {
  const html = readFileSync(join(dist, entryHtml), 'utf8');
  const seeds = [...html.matchAll(/(?:src|href)="([^"]+\.js)"/g)].map((m) => basename(m[1]));
  const seen = new Set<string>();
  const queue = [...seeds];
  while (queue.length > 0) {
    const name = queue.shift();
    if (name === undefined || seen.has(name)) {
      continue;
    }
    const path = join(dist, 'assets', name);
    if (!existsSync(path)) {
      continue;
    }
    seen.add(name);
    const code = readFileSync(path, 'utf8');
    for (const match of code.matchAll(STATIC_IMPORT)) {
      queue.push(basename(match[1]));
    }
  }

  return [...seen].sort();
}

const VLQ = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/** Which half of the tree a module belongs to — the split 1/01 read the bundle by. */
function byArea(sources: readonly SourceReading[]): [string, number][] {
  const areas = new Map<string, number>();
  for (const { bytes, source } of sources) {
    const area = /node_modules\/(?:\.pnpm\/)?((?:@[^/]+\/)?[^/]+)/.exec(source)?.[1]
      ? `node_modules: ${/node_modules\/(?:\.pnpm\/)?((?:@[^/]+\/)?[^/]+)/.exec(source)?.[1]}`
      : (/(?:^|\/)((?:packages|apps|tools)\/[^/]+)/.exec(source)?.[1] ?? source);
    areas.set(area, (areas.get(area) ?? 0) + bytes);
  }

  return [...areas.entries()].sort((a, b) => b[1] - a[1]);
}

function decodeVlq(segment: string): number[] {
  const out: number[] = [];
  let shift = 0;
  let value = 0;
  for (const char of segment) {
    const digit = VLQ.indexOf(char);
    const more = (digit & 32) !== 0;
    value += (digit & 31) << shift;
    if (more) {
      shift += 5;
      continue;
    }
    const negative = (value & 1) === 1;
    value >>= 1;
    out.push(negative ? -value : value);
    shift = 0;
    value = 0;
  }

  return out;
}

function kb(bytes: number): string {
  return `${(bytes / 1024).toFixed(1)} kB`;
}

function main(): void {
  const dist = argValue('--dist', 'dist');
  const entry = argValue('--entry', 'dispatch.html');
  const top = Number(argValue('--top', '25'));
  if (!existsSync(join(dist, entry))) {
    throw new Error(`no ${entry} under ${dist}/ — run: npm run build -- --base=./ --sourcemap`);
  }

  const chunks: ChunkReading[] = reachableChunks(dist, entry).map((name) => {
    const raw = readFileSync(join(dist, 'assets', name));

    return { bytesGzip: gzipSync(raw).byteLength, bytesRaw: raw.byteLength, name };
  });
  chunks.sort((a, b) => b.bytesRaw - a.bytesRaw);
  const totalRaw = chunks.reduce((sum, c) => sum + c.bytesRaw, 0);
  const totalGzip = chunks.reduce((sum, c) => sum + c.bytesGzip, 0);

  const sources = chunks.flatMap((c) => attribute(dist, c.name)).sort((a, b) => b.bytes - a.bytes);
  const mappedTotal = sources.reduce((sum, s) => sum + s.bytes, 0);

  console.log(`${entry}: ${chunks.length} chunks, ${kb(totalRaw)} raw / ${kb(totalGzip)} gzip`);
  console.log('\nchunks (static import graph only — an import() chunk is downloaded later, not shipped):');
  for (const c of chunks) {
    console.log(`  ${kb(c.bytesRaw).padStart(10)} raw  ${kb(c.bytesGzip).padStart(10)} gzip   ${c.name}`);
  }
  if (sources.length === 0) {
    console.log('\nNo sourcemaps beside the chunks — rebuild with --sourcemap for the per-module table.');

    return;
  }
  console.log(`\ntop ${top} sources (of ${sources.length}, ${kb(mappedTotal)} attributed):`);
  for (const s of sources.slice(0, top)) {
    const share = ((100 * s.bytes) / totalRaw).toFixed(1);
    console.log(`  ${kb(s.bytes).padStart(10)}  ${share.padStart(5)} %  ${s.source}`);
  }
  console.log('\nby area:');
  for (const [area, bytes] of byArea(sources)) {
    console.log(`  ${kb(bytes).padStart(10)}  ${((100 * bytes) / totalRaw).toFixed(1).padStart(5)} %  ${area}`);
  }

  const jsonPath = argValue('--json', '');
  if (jsonPath !== '') {
    const report = { chunks, entry, sources, totals: { bytesGzip: totalGzip, bytesRaw: totalRaw } };
    writeFileSync(jsonPath, `${JSON.stringify(report, null, 2)}\n`);
    process.stdout.write(`\nwritten: ${jsonPath}\n`);
  }
}

main();
