/**
 * cutscene-override-ini — generate `cutscene-override.ini` for the CLEO cutscene-override script
 * (cleo/scripts plan 003): the comment head lists every cutscene in `anim/cuts.img` that drives a
 * cutscene VEHICLE (ANPK `NAME` chunks matched against the vehicle-cutscene census), `[cutscene]`
 * ships an empty `scene =` (the script stays inert until a name is written in), and `[areas]`
 * carries the interior area main.scm sets before each of its `02E4` sites (nearest-`04BB` decode;
 * a scene without a row plays in area 0).
 *
 * Run: `npx tsx scripts/debug/cutscene-override-ini.ts [--out <path>] [--game <game>]`
 *      `npx tsx scripts/debug/cutscene-override-ini.ts --out NO_COMMIT/cleo-stage/cutscene-override.ini`
 */
import { openArchive } from '@opensa/renderware/archive/img-archive';
import { readFileSync, writeFileSync } from 'node:fs';

import { loadCensus } from '../../tools/vehicle-cutscene/src/census';
import { gameArg, gameDir } from '../lib/game';

const game = gameArg();
const outIndex = process.argv.indexOf('--out');
const outPath = outIndex >= 0 ? process.argv[outIndex + 1] : null;

const csNames = new Set(loadCensus(gameDir(game)).slots.map((slot) => slot.csName));

// scene → cs vehicles it drives, from each .ifp's ANPK NAME chunks
const cuts = openArchive(new Uint8Array(readFileSync(gameDir(game, 'anim', 'cuts.img'))));
const sceneVehicles = new Map<string, string[]>();
for (const entry of cuts.names) {
  if (!entry.toLowerCase().endsWith('.ifp')) continue;
  const bytes = cuts.get(entry);
  if (!bytes) continue;
  const vehicles = [...anpkObjectNames(new Uint8Array(bytes))].filter((name) => csNames.has(name)).sort();
  if (vehicles.length > 0) {
    sceneVehicles.set(entry.slice(0, -'.ifp'.length).toUpperCase(), vehicles);
  }
}

// scene → world site, from each .cut's own `info / offset x y z` (the origin the engine itself
// reads — the override warps the player there so the world streams around the scene)
const sceneSites = new Map<string, [string, string, string]>();
for (const entry of cuts.names) {
  if (!entry.toLowerCase().endsWith('.cut')) continue;
  const bytes = cuts.get(entry);
  if (!bytes) continue;
  const match = /^\s*offset\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)/m.exec(Buffer.from(bytes).toString('latin1'));
  if (match) {
    sceneSites.set(entry.slice(0, -'.cut'.length).toUpperCase(), [match[1], match[2], match[3]]);
  }
}

// scene → interior area, from main.scm: the nearest 04BB SET_AREA_VISIBLE before each 02E4 site
const scm = readFileSync(gameDir(game, 'data', 'script', 'main.scm'));
const areas = new Map<string, number>();
for (let i = 4; i + 10 < scm.length; i++) {
  if (scm[i] !== 0xe4 || scm[i + 1] !== 0x02 || scm[i + 2] !== 0x09) continue;
  const raw = scm.subarray(i + 3, i + 11);
  const end = raw.indexOf(0);
  const name = raw.subarray(0, end === -1 ? 8 : end).toString('latin1');
  if (!/^[\x20-\x7e]+$/.test(name)) continue;
  const area = nearestAreaBefore(i);
  if (area !== null && area !== 0) {
    areas.set(name.toUpperCase(), area);
  }
}

const sceneRows = [...sceneVehicles.entries()].sort(([a], [b]) => a.localeCompare(b));
const lines = [
  '; cutscene-override — write a scene name into [cutscene] scene= and it plays at new game',
  '; (or right after loading a save). Empty scene = the override script stays inert.',
  `; GENERATED by scripts/debug/cutscene-override-ini.ts — do not hand-maintain the lists.`,
  ';',
  '; vehicle cutscenes (scene = cs vehicles it drives):',
  ...sceneRows.map(([scene, vehicles]) => `;   ${scene.padEnd(8)} = ${vehicles.join(', ')}`),
  ';',
  '; [areas] is the interior area main.scm sets before starting that scene; a scene without a',
  '; row plays in area 0 (outside). A scene that shows empty blue void has an unrecorded area.',
  "; [sitex]/[sitey]/[sitez] carry each scene's world site from the .cut's own offset row — the",
  '; override warps the player there (under the fade) so the world streams around the scene.',
  '',
  '[cutscene]',
  'scene =',
  '',
  '[areas]',
  ...[...areas.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([scene, area]) => `${scene}=${area}`),
  ...(['sitex', 'sitey', 'sitez'] as const).flatMap((section, axis) => [
    '',
    `[${section}]`,
    ...[...sceneSites.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([scene, site]) => `${scene}=${site[axis]}`),
  ]),
  '',
];

const text = lines.join('\n');
const summary = `${sceneRows.length} vehicle scenes, ${areas.size} area rows, ${sceneSites.size} site sections`;
if (outPath) {
  writeFileSync(outPath, text);
  console.log(`wrote ${outPath}: ${summary}`);
} else {
  console.log(text);
  console.error(`\n${summary}`);
}

/** All ANPK `NAME` chunk values (lowercased) — the objects the scene's anims drive. */
function anpkObjectNames(data: Uint8Array): Set<string> {
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const names = new Set<string>();
  const tag = (at: number): string => String.fromCharCode(data[at], data[at + 1], data[at + 2], data[at + 3]);
  const align = (value: number): number => (value + 3) & ~3;
  let pos = 8; // inside the ANPK container
  while (pos + 8 <= data.length) {
    const kind = tag(pos);
    const size = view.getUint32(pos + 4, true);
    if (kind === 'NAME') {
      const raw = Buffer.from(data.subarray(pos + 8, pos + 8 + size)).toString('latin1');
      names.add(raw.split('\0')[0].toLowerCase());
      pos = align(pos + 8 + size);
    } else if (kind === 'DGAN' || kind === 'CPAN') {
      pos += 8; // containers: descend
    } else {
      pos = align(pos + 8 + size); // ANIM / INFO / keyframe blocks / unknowns
    }
  }

  return names;
}

/**
 * The area the nearest `04BB SET_AREA_VISIBLE` before a `02E4` site sets (immediate args only), or
 * null when none sits within 64 bytes — main.scm's second-scene-of-a-mission sites inherit the area
 * from earlier flow, which this deliberately does not chase.
 */
function nearestAreaBefore(site: number): null | number {
  for (let i = site - 3; i >= site - 64 && i >= 0; i--) {
    if (scm[i] !== 0xbb || scm[i + 1] !== 0x04) continue;
    const type = scm[i + 2];
    if (type === 0x04) return scm[i + 3];
    if (type === 0x05) return scm.readInt16LE(i + 3);
    if (type === 0x01) return scm.readInt32LE(i + 3);

    return null; // a variable arg — not decodable statically
  }

  return null;
}
