import { buildVer2Buffer, openArchive } from '@opensa/renderware/archive';
import { existsSync, readFileSync } from 'node:fs';
import { afterEach, describe, expect, it, vi } from 'vitest';

import type { ByteRangeSource } from './img-reader';

import { openLazyVer2, urlRangeSource } from './img-reader';

/** An in-memory {@link ByteRangeSource} that records every slice range, so we can assert laziness. */
function memorySource(bytes: Uint8Array): { reads: [number, number][]; source: ByteRangeSource } {
  const reads: [number, number][] = [];

  return {
    reads,
    source: {
      size: bytes.length,
      slice: (start, end): Promise<Uint8Array> => {
        reads.push([start, end]);

        return Promise.resolve(bytes.subarray(start, end));
      },
    },
  };
}

const ARCHIVE = buildVer2Buffer([
  { data: new Uint8Array([1, 2, 3, 4]), name: 'alpha.dff' },
  { data: new Uint8Array([9, 8, 7]), name: 'beta.txd' },
]);

describe('openLazyVer2', () => {
  describe('negative cases', () => {
    it('throws when the magic is not VER2', async () => {
      const { source } = memorySource(new Uint8Array(64)); // all zeroes → no "VER2" header

      await expect(openLazyVer2(source)).rejects.toThrow(/VER2/);
    });

    it('reads null for an unknown entry without slicing data', async () => {
      const { reads, source } = memorySource(ARCHIVE);
      const archive = await openLazyVer2(source);
      const before = reads.length;

      expect(await archive.read('missing.dff')).toBeNull();
      expect(reads.length).toBe(before); // no data slice for an absent name
    });
  });

  describe('positive cases', () => {
    it('lists entry names (lowercased) from the directory alone', async () => {
      const { source } = memorySource(ARCHIVE);
      const archive = await openLazyVer2(source);

      expect(archive.names.sort()).toEqual(['alpha.dff', 'beta.txd']);
      expect(archive.has('ALPHA.DFF')).toBe(true);
    });

    it('reads an entry by name (case-insensitive), returning its stored bytes', async () => {
      const { source } = memorySource(ARCHIVE);
      const archive = await openLazyVer2(source);

      expect(Array.from((await archive.read('ALPHA.dff'))!.subarray(0, 4))).toEqual([1, 2, 3, 4]);
      expect(Array.from((await archive.read('beta.txd'))!.subarray(0, 3))).toEqual([9, 8, 7]);
    });

    it('does not buffer the whole archive — only directory + the requested entry are sliced', async () => {
      const { reads, source } = memorySource(ARCHIVE);
      const archive = await openLazyVer2(source);
      await archive.read('alpha.dff');

      // header(0,8) + directory(0,dirLen) + one entry range — never a [0, size] full read.
      expect(reads.some(([start, end]) => start === 0 && end === source.size)).toBe(false);
    });
  });
});

// A real stock VER2 archive (regenerated by `npm run test:fixtures` into the gitignored fixtures/original).
const REAL_IMG = 'fixtures/original/img/admiral.img';

describe.skipIf(!existsSync(REAL_IMG))('openLazyVer2 (real admiral.img)', () => {
  describe('positive cases', () => {
    it('reads the same entry bytes as the eager openArchive (parity)', async () => {
      const bytes = new Uint8Array(readFileSync(REAL_IMG));
      const { source } = memorySource(bytes);
      const lazy = await openLazyVer2(source);
      const eager = openArchive(bytes);

      expect(lazy.names).toEqual(eager.names);
      const name = lazy.names[0];
      expect(Array.from((await lazy.read(name))!)).toEqual(Array.from(new Uint8Array(eager.get(name)!)));
    });
  });
});

describe('urlRangeSource', () => {
  afterEach(() => vi.unstubAllGlobals());

  describe('negative cases', () => {
    it('rejects when the range fetch is not ok', async () => {
      vi.stubGlobal('fetch', () => Promise.resolve({ ok: false, status: 416 } as Response));

      await expect(urlRangeSource('http://host/f', 100).slice(0, 4)).rejects.toThrow(
        /range fetch 416: http:\/\/host\/f/,
      );
    });
  });

  describe('positive cases', () => {
    it('sends a Range header over [start, end) and returns the sliced bytes', async () => {
      let header = '';
      vi.stubGlobal('fetch', (_input: string, init: { headers: { Range: string } }) => {
        header = init.headers.Range;

        return Promise.resolve({ arrayBuffer: () => Promise.resolve(new Uint8Array([9, 8, 7, 6]).buffer), ok: true });
      });

      const bytes = await urlRangeSource('http://host/f', 100).slice(8, 12);
      expect(header).toBe('bytes=8-11');
      expect(Array.from(bytes)).toEqual([9, 8, 7, 6]);
    });
  });
});
