import { parseDff } from '@opensa/renderware/parsers/binary/dff';
import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import type { Asset } from '../core/asset';

import { clumpToIr } from '../adapters/gta-sa/read';
import { createSmoothNormals, emptySmoothNormalsStats } from './smooth-normals';

/**
 * Real-asset gate check (plan 024 Family A) over the Map Fixes Pack `lae2_roads17` — the field case
 * that opened the plan: a two-sided road tile whose authored normals are winding-CONSISTENT (mirror
 * sides agree with their own winding, shared-vertex evidence cancels) yet 35 point DOWN and 61
 * sideways on a horizontal road, rendering as dark Gouraud wedges. The 020 gate PRESERVED them
 * (failing = 0); the 024 `badShading` check must fail enough of them to force a full recompute, and
 * the recomputed normals must leave no visible face referencing a ground-facing vertex normal.
 * The DFF comes from `mods-src` (regenerated by `npm run test:fixtures` into the gitignored
 * `fixtures/original/`).
 */
const FIXTURE = 'fixtures/original/mods/lae2_roads17.dff';
const haveFixture = existsSync(FIXTURE);

/** Faces whose face normal points up (z > 0.5) yet reference a vertex normal with nz < 0.5. */
function darkTopFaces(asset: Asset): number {
  let bad = 0;
  for (const mesh of asset.ir.meshes) {
    const n = mesh.normals;
    if (!n) continue;
    const p = mesh.positions;
    for (const t of mesh.triangles) {
      const ux = p[t.b * 3] - p[t.a * 3];
      const uy = p[t.b * 3 + 1] - p[t.a * 3 + 1];
      const uz = p[t.b * 3 + 2] - p[t.a * 3 + 2];
      const vx = p[t.c * 3] - p[t.a * 3];
      const vy = p[t.c * 3 + 1] - p[t.a * 3 + 1];
      const vz = p[t.c * 3 + 2] - p[t.a * 3 + 2];
      const fz = ux * vy - uy * vx;
      const flen = Math.hypot(uy * vz - uz * vy, uz * vx - ux * vz, fz);
      if (flen < 1e-9 || fz / flen < 0.5) continue;
      for (const v of [t.a, t.b, t.c]) {
        const nlen = Math.hypot(n[v * 3], n[v * 3 + 1], n[v * 3 + 2]) || 1;
        if (n[v * 3 + 2] / nlen < 0.5) {
          bad += 1;
          break;
        }
      }
    }
  }

  return bad;
}

function loadAsset(): Asset {
  const bytes = readFileSync(FIXTURE);
  const source = new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const clump = parseDff(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));

  return { dirty: false, ir: clumpToIr(clump), log: [], meta: {}, name: 'lae2_roads17', source };
}

describe.skipIf(!haveFixture)('smooth-normals gate on lae2_roads17 (real asset, plan 024)', () => {
  describe('negative cases', () => {
    it('the source really is the broken class: top faces referencing ground-facing normals', () => {
      expect(darkTopFaces(loadAsset())).toBeGreaterThan(10);
    });
  });

  describe('positive cases', () => {
    it('the badShading gate forces a full recompute and the rebuilt top surface is clean', () => {
      const asset = loadAsset();
      const stats = emptySmoothNormalsStats();
      const plugin = createSmoothNormals({ addWhereAbsent: true }, stats);
      void plugin.transform(asset, { game: 'test', log: (): void => undefined });

      expect(stats.recomputedMeshes).toBe(1); // 020 preserved this mesh; 024 must not
      expect(stats.preservedMeshes).toBe(0);
      expect(darkTopFaces(asset)).toBe(0);
    });
  });
});
