import { parseDff } from '@opensa/renderware/parsers/binary/dff';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { readRw, RW_CLUMP, RW_EXTENSION, RW_GEOMETRY, RW_GEOMETRY_LIST, RW_TWO_D_EFFECT } from './chunk';
import { collectGeometries, stripParticleEffects } from './dff';

function chunk(type: number, body: Uint8Array): Uint8Array {
  return concat([u32(type), u32(body.length), u32(0), body]);
}

function concat(parts: readonly Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((sum, part) => sum + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }

  return out;
}

/** A 2dfx entry: position (3×f32, zeroed here) + type + dataSize + data. */
function entry(type: number, data: Uint8Array): Uint8Array {
  return concat([new Uint8Array(12), u32(type), u32(data.length), data]);
}

function u32(value: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, value, true);

  return out;
}

const LIGHT = entry(0, new Uint8Array(4).fill(1));
const PARTICLE = entry(1, new Uint8Array(24).fill(9));
const ROADSIGN = entry(7, new Uint8Array(8).fill(2));

/** A minimal clump: CLUMP → GEOMETRY_LIST → GEOMETRY → EXTENSION → 2dfx(entries). */
function clumpWith2dfx(entries: Uint8Array, count: number): Uint8Array {
  const fx = chunk(RW_TWO_D_EFFECT, concat([u32(count), entries]));
  const geometry = chunk(RW_GEOMETRY, chunk(RW_EXTENSION, fx));

  return chunk(RW_CLUMP, chunk(RW_GEOMETRY_LIST, geometry));
}

/** The parsed 2dfx section of the first geometry: its entry count + each entry's type, in order. */
function read2dfx(bytes: Uint8Array): { count: number; types: number[] } {
  const geometry = collectGeometries(readRw(bytes).chunks)[0];
  const extension = geometry.children?.find((child) => child.type === RW_EXTENSION);
  const data = extension?.children?.find((child) => child.type === RW_TWO_D_EFFECT)?.data;
  if (!data) {
    return { count: 0, types: [] };
  }
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  const count = view.getUint32(0, true);
  const types: number[] = [];
  let pos = 4;
  for (let i = 0; i < count; i += 1) {
    types.push(view.getUint32(pos + 12, true));
    pos += 20 + view.getUint32(pos + 16, true);
  }

  return { count, types };
}

describe('stripParticleEffects', () => {
  describe('negative cases', () => {
    it('returns the input unchanged when there is no 2dfx section', () => {
      const bytes = chunk(RW_CLUMP, chunk(RW_GEOMETRY_LIST, chunk(RW_GEOMETRY, new Uint8Array(0))));

      expect(stripParticleEffects(bytes)).toBe(bytes);
    });

    it('returns the input unchanged when the 2dfx section has no particle entries', () => {
      const bytes = clumpWith2dfx(concat([LIGHT, ROADSIGN]), 2);

      expect(stripParticleEffects(bytes)).toBe(bytes);
    });
  });

  describe('positive cases', () => {
    it('removes the particle entry and keeps the light', () => {
      const stripped = stripParticleEffects(clumpWith2dfx(concat([LIGHT, PARTICLE]), 2));

      expect(read2dfx(stripped)).toEqual({ count: 1, types: [0] });
    });

    it('removes every particle while keeping other entry types in order', () => {
      const stripped = stripParticleEffects(clumpWith2dfx(concat([PARTICLE, LIGHT, PARTICLE, ROADSIGN]), 4));

      expect(read2dfx(stripped)).toEqual({ count: 2, types: [0, 7] });
    });
  });
});

// A real refinery chimney: a smoke particle emitter + 3 light coronas + day/night colours (regenerated by
// `npm run test:fixtures` from a clean SA install — Rockstar asset, gitignored).
const CHIMNEY = 'fixtures/original/dff/particle/refchimny01.dff';
const ab = (u: Uint8Array): ArrayBuffer => u.buffer.slice(u.byteOffset, u.byteOffset + u.byteLength) as ArrayBuffer;

describe('stripParticleEffects (real fixture)', () => {
  describe('positive cases', () => {
    const source = (): Uint8Array => new Uint8Array(readFileSync(CHIMNEY));

    it('drops the smoke particle but keeps the light coronas and the geometry', () => {
      const before = parseDff(ab(source())).geometries[0];
      expect((before.particles ?? []).length).toBeGreaterThan(0); // fixture sanity: has a particle...
      expect(before.lights.length).toBe(3); // ...and light coronas

      const after = parseDff(ab(stripParticleEffects(source()))).geometries[0];
      expect(after.particles ?? []).toHaveLength(0); // particle gone
      expect(after.lights.length).toBe(3); // coronas kept
      expect(after.triangles.length).toBe(before.triangles.length); // geometry untouched
    });
  });
});
