/**
 * Pure planning + IPL-text helpers for the int16 "ghost barriers" repro dial (tools-debug/sa-int16-repro/docs).
 * No filesystem here — {@link inflate} in `inflate.ts` drives these against a built game dir.
 *
 * The bug: SA stores building-pool indexes as int16 in `IplDef::firstBuilding/lastBuilding`
 * (`CIplStore::IncludeEntity` @0x404C90). Permanent (text-IPL) instances fill the pool's low indexes at boot;
 * once there are more than 32,767 of them, every binary-streamed instance lands above int16 range, the recorded
 * ranges wrap negative, and stream-out (`RemoveIpl`) deletes/keeps arbitrary entities — the ghost `barriers2`.
 * This dial adds trivial dummy text rows to push the map-wide total across 2^15 on demand.
 */

/** SA's `IplEntityIndexArrays` usable capacity — one slot per gta.dat text IPL with inst rows (40 declared, the
 *  40th crashed in-game, so 39 is the hard line). Mirror of perfect-map-builder's `TEXT_IPL_SLOT_CAP`. The repro
 *  MUST stay under this so a crash past 2^15 is attributable to int16 alone, not to slot overflow. */
export const TEXT_IPL_SLOT_CAP = 39;

/** 2^15 — the exact flip point bisected in the post-mortem (31,300 rows → clean; 33,210 → bug). */
export const INT16_ROW_CEILING = 32768;

/** Rows per synthetic filler text IPL. SA overflows a 4096-pointer static buffer (`gpLoadedBuildings`,
 *  `CFileLoader::LoadScene`) while loading ONE text IPL + its boot streams; filler areas carry no streams, so
 *  4000 rows leaves margin and keeps that structure out of the picture. */
export const FILLER_ROWS_PER_AREA = 4000;

export interface DummyModel {
  readonly id: number;
  readonly name: string;
}

export interface InflationPlan {
  /** Rows the dial must add to reach `targetRows`. */
  readonly addRows: number;
  readonly fillerAreas: number;
  readonly fillerRows: number;
  /** New text-IPL slots this build introduces (one per filler area). */
  readonly newSlots: number;
  readonly totalRows: number;
  readonly totalSlots: number;
}

export type Vec3 = readonly [number, number, number];

/** An IPL `inst` section of trivial rows — all the same valid stock model id (guaranteed loadable), `lod` −1. */
export function fillerIplText(model: DummyModel, positions: readonly Vec3[]): string {
  const rows = positions.map(([x, y, z]) => `${model.id}, ${model.name}, 0, ${x}, ${y}, ${z}, 0, 0, 0, 1, -1`);

  return ['# Generated by @opensa/sa-int16-repro — synthetic int16 row filler', 'inst', ...rows, 'end', ''].join(
    '\r\n',
  );
}

/**
 * `count` positions on a flat grid far outside the playable map (default z −1000, well beyond the ±3000 world) —
 * the filler entities exist only to occupy building-pool slots at boot; they are never streamed near the player,
 * so their location is irrelevant to the count-driven bug and safely invisible.
 */
export function gridPositions(count: number, origin: Vec3, step = 4, cols = 128): Vec3[] {
  const out: Vec3[] = [];
  for (let i = 0; i < count; i += 1) {
    out.push([origin[0] + (i % cols) * step, origin[1] + Math.floor(i / cols) * step, origin[2]]);
  }

  return out;
}

/**
 * Work out how to reach `targetRows` total permanent text rows from a base build: how many rows to add, how many
 * dense filler areas that needs, and the resulting slot count. Throws when the base already meets/exceeds the
 * target (nothing to add) — the dial only inflates.
 */
export function planInflation(input: {
  readonly baseRows: number;
  readonly baseSlots: number;
  readonly targetRows: number;
}): InflationPlan {
  const addRows = input.targetRows - input.baseRows;
  if (addRows <= 0) {
    throw new Error(
      `base already has ${input.baseRows} text rows ≥ target ${input.targetRows} — pick a lower base build or a higher --rows`,
    );
  }
  const fillerAreas = Math.ceil(addRows / FILLER_ROWS_PER_AREA);

  return {
    addRows,
    fillerAreas,
    fillerRows: addRows,
    newSlots: fillerAreas,
    totalRows: input.targetRows,
    totalSlots: input.baseSlots + fillerAreas,
  };
}
