/**
 * The camera config the rig tests run against — the SHIPPED defaults, written out literally.
 *
 * Deliberately a copy rather than `createGameRuntimeConfig().camera`: a field round retunes those numbers,
 * and a behaviour test that silently follows the tuning stops testing the behaviour. When a default moves,
 * this fixture moves with it only if the tests still describe what the rig should do.
 */
import type { CameraConfig } from '@opensa/game';

export const TEST_CAMERA_CONFIG: CameraConfig = {
  bobAmplitude: 0.025,
  bobCyclesPerMetre: 0.25,
  collisionMinDistance: 0.5,
  collisionRadius: 0.35,
  collisionReleaseTime: 0.4,
  collisionWhiskerAngle: 0,
  deadZone: 0.08,
  driftLookBlend: 0.5,
  driftMinSpeed: 6,
  driftSlipDeadZone: 0.05,
  followDistance: 7,
  followHeight: 0.9,
  followLerp: 3,
  followMaxPolar: Math.PI / 2 - 0.05,
  followMinPolar: 0.25,
  followPolar: 1.15,
  followZoom: true,
  followZoomMax: 10,
  followZoomMin: 4,
  footIdleDelaySec: 5,
  footIdleDistanceEase: 0.4,
  footRunDistanceGain: 0.6,
  footRunFullSpeed: 7,
  footYawAuthorityFull: 0.9,
  footYawAuthorityStart: 0.2,
  inputSmoothTime: 0.03,
  lagMaxDistance: 1.2,
  landingDipFullSpeed: 5,
  landingDipScale: 0.22,
  lookAheadDistance: 0.8,
  lookAheadFullSpeed: 7,
  lookAheadTime: 0.45,
  manualGraceSec: 0.25,
  moveThreshold: 0.6,
  pitchMax: 0.9,
  pitchMin: -1.2,
  positionLagTime: 0.12,
  recenterDelaySec: 2,
  recenterRate: 1.6,
  reducedMotion: false,
  sensitivity: 0.004,
  settleEpsilon: 0.03,
  shakeImpactForce: 250000,
  shakeScale: 0.08,
  sprintFovKick: 0.07,
  teleportSnapDistance: 20,
  turnThreshold: 0.9,
  vehicleAccelDistanceGain: 1,
  vehicleCollisionReleaseTime: 0.6,
  vehicleDistanceGain: 5,
  vehicleDistanceScale: 1,
  vehicleDistanceSpeed: 40,
  vehicleFovKick: 0.175,
  vehicleFovLambda: 2.5,
  vehicleFovMaxSpeed: 28,
  vehicleFovMinSpeed: 6,
  vehicleRecenterDelaySec: 1.5,
  vehicleVerticalLagTime: 0.15,
  vehicleYawLagTime: 0.35,
  verticalLagTime: 0.28,
  yawLagTime: 0.25,
  zoomLambda: 8,
};
